// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_command
Rcpp::List run_command(Rcpp::DataFrame df, Rcpp::IntegerVector es, int tau, Rcpp::NumericVector thetas, Rcpp::Nullable<Rcpp::IntegerVector> libs, int k, std::string algorithm, int numReps, int p, int crossfold, bool full, bool shuffle, bool saveFinalPredictions, bool saveFinalCoPredictions, bool saveManifolds, bool saveSMAPCoeffs, bool dt, bool reldt, double dtWeight, Rcpp::Nullable<Rcpp::List> extras, bool allowMissing, double missingDistance, double panelWeight, int verbosity, int numThreads, bool lowMemory, std::string saveInputs);
RcppExport SEXP _fastEDM_run_command(SEXP dfSEXP, SEXP esSEXP, SEXP tauSEXP, SEXP thetasSEXP, SEXP libsSEXP, SEXP kSEXP, SEXP algorithmSEXP, SEXP numRepsSEXP, SEXP pSEXP, SEXP crossfoldSEXP, SEXP fullSEXP, SEXP shuffleSEXP, SEXP saveFinalPredictionsSEXP, SEXP saveFinalCoPredictionsSEXP, SEXP saveManifoldsSEXP, SEXP saveSMAPCoeffsSEXP, SEXP dtSEXP, SEXP reldtSEXP, SEXP dtWeightSEXP, SEXP extrasSEXP, SEXP allowMissingSEXP, SEXP missingDistanceSEXP, SEXP panelWeightSEXP, SEXP verbositySEXP, SEXP numThreadsSEXP, SEXP lowMemorySEXP, SEXP saveInputsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type es(esSEXP);
    Rcpp::traits::input_parameter< int >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type thetas(thetasSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type libs(libsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::string >::type algorithm(algorithmSEXP);
    Rcpp::traits::input_parameter< int >::type numReps(numRepsSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type crossfold(crossfoldSEXP);
    Rcpp::traits::input_parameter< bool >::type full(fullSEXP);
    Rcpp::traits::input_parameter< bool >::type shuffle(shuffleSEXP);
    Rcpp::traits::input_parameter< bool >::type saveFinalPredictions(saveFinalPredictionsSEXP);
    Rcpp::traits::input_parameter< bool >::type saveFinalCoPredictions(saveFinalCoPredictionsSEXP);
    Rcpp::traits::input_parameter< bool >::type saveManifolds(saveManifoldsSEXP);
    Rcpp::traits::input_parameter< bool >::type saveSMAPCoeffs(saveSMAPCoeffsSEXP);
    Rcpp::traits::input_parameter< bool >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< bool >::type reldt(reldtSEXP);
    Rcpp::traits::input_parameter< double >::type dtWeight(dtWeightSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type extras(extrasSEXP);
    Rcpp::traits::input_parameter< bool >::type allowMissing(allowMissingSEXP);
    Rcpp::traits::input_parameter< double >::type missingDistance(missingDistanceSEXP);
    Rcpp::traits::input_parameter< double >::type panelWeight(panelWeightSEXP);
    Rcpp::traits::input_parameter< int >::type verbosity(verbositySEXP);
    Rcpp::traits::input_parameter< int >::type numThreads(numThreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type lowMemory(lowMemorySEXP);
    Rcpp::traits::input_parameter< std::string >::type saveInputs(saveInputsSEXP);
    rcpp_result_gen = Rcpp::wrap(run_command(df, es, tau, thetas, libs, k, algorithm, numReps, p, crossfold, full, shuffle, saveFinalPredictions, saveFinalCoPredictions, saveManifolds, saveSMAPCoeffs, dt, reldt, dtWeight, extras, allowMissing, missingDistance, panelWeight, verbosity, numThreads, lowMemory, saveInputs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastEDM_run_command", (DL_FUNC) &_fastEDM_run_command, 27},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastEDM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
