# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_command <- function(df, es, libs, ropts, tau, p, numReps = 1L, crossfold = 0L, full = FALSE, dtMode = FALSE, allowMissing = FALSE, verbosity = 1L) {
    .Call('_fastEDM_run_command', PACKAGE = 'fastEDM', df, es, libs, ropts, tau, p, numReps, crossfold, full, dtMode, allowMissing, verbosity)
}

run_json_test <- function(fnameIn) {
    .Call('_fastEDM_run_json_test', PACKAGE = 'fastEDM', fnameIn)
}

rcppeigen_hello_world <- function() {
    .Call('_fastEDM_rcppeigen_hello_world', PACKAGE = 'fastEDM')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_fastEDM_rcppeigen_outerproduct', PACKAGE = 'fastEDM', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_fastEDM_rcppeigen_innerproduct', PACKAGE = 'fastEDM', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_fastEDM_rcppeigen_bothproducts', PACKAGE = 'fastEDM', x)
}

