# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_command <- function(df, es, tau, thetas, libs, k = 0L, algorithm = "simplex", numReps = 1L, p = 1L, crossfold = 0L, full = FALSE, shuffle = FALSE, saveFinalPredictions = FALSE, saveFinalCoPredictions = FALSE, saveManifolds = FALSE, saveSMAPCoeffs = FALSE, dt = FALSE, reldt = FALSE, dtWeight = 0.0, extras = NULL, allowMissing = FALSE, missingDistance = 0.0, panelWeight = 0.0, verbosity = 1L, numThreads = 1L, lowMemory = FALSE, predictWithPast = FALSE, saveInputs = "") {
    .Call(`_fastEDM_run_command`, df, es, tau, thetas, libs, k, algorithm, numReps, p, crossfold, full, shuffle, saveFinalPredictions, saveFinalCoPredictions, saveManifolds, saveSMAPCoeffs, dt, reldt, dtWeight, extras, allowMissing, missingDistance, panelWeight, verbosity, numThreads, lowMemory, predictWithPast, saveInputs)
}

